---
title: "Indicator species by cluster"
output: html_notebook
---

# Set Up
## Load Libs
```{r}
library(indicspecies)
source("R/common.R", local = knitr::knit_global())
```

## Constants
```{r}
SOME_SEED = 7442
```

## Helper functions
```{r}
to_indicator_species_matrix = function(per_site) {
  per_site %>% dplyr::select(-title) %>% mutate(across(everything(), as.integer)) %>% as.matrix
}
```

# Clusters
## Plant and Insect
```{r}
plant_and_insect_clusters = read_input_csv('insect-plant-clusters.csv') %>% tranpose_cluster_df()
plant_and_insect_clusters
```

```{r}
bird_clusters = read_input_csv('bird-clusters.csv') %>% tranpose_cluster_df()
bird_clusters
```

# Species Presence
```{r}
insects_per_site = read_input_csv('insect-presence.csv') %>% 
  to_presence_dataframe() %>% 
  include_sites_with_no_presence_record(plant_and_insect_clusters$title) %>% 
  arrange(title)
insects_per_site
```

```{r}
plants_per_site = read_input_csv('plant-presence.csv') %>% 
  to_presence_dataframe() %>% 
  include_sites_with_no_presence_record(plant_and_insect_clusters$title) %>% 
  arrange(title)
plants_per_site
```

```{r}
birds_per_site = read_input_csv('bird-presence.csv') %>% 
  to_presence_dataframe() %>% 
  include_sites_with_no_presence_record(bird_clusters$title) %>% 
  arrange(title)
birds_per_site
```

# Insect Indicators
## (k = 3)
```{r}
insects_per_site_matrix = to_indicator_species_matrix(insects_per_site)
plants_per_site_matrix = to_indicator_species_matrix(plants_per_site)
birds_per_site_matrix = to_indicator_species_matrix(birds_per_site)

indicator_species = function(species_matrix, cluster_assignment) {
  set.seed(SOME_SEED)
  cluster_fact = factor(cluster_assignment)
  multipatt(species_matrix, cluster_fact, control = how(nperm=999))
}

insect_indicator_species = function(cluster_assignment) {indicator_species(insects_per_site_matrix, cluster_assignment)}
plant_indicator_species = function(cluster_assignment) {indicator_species(plants_per_site_matrix, cluster_assignment)}
bird_indicator_species = function(cluster_assignment) {indicator_species(birds_per_site_matrix, cluster_assignment)}

insects_k3 = insect_indicator_species(plant_and_insect_clusters$`3`)
summary(insects_k3)
```

```{r}
as.data.frame(insects_k3$sign)
```

```{r}
indicator_species_stats = function(k, indicator_results) {
  not_generalist_species = nrow(indicator_results$sign[!is.na(indicator_results$sign$p.value),])
  
  data.frame(
    k = k,
    number_not_generalist = not_generalist_species,
    proportion_not_generalist = not_generalist_species / nrow(indicator_results$sign),
    average_p_value = mean(indicator_results$sign$p.value, na.rm = T)
  )
}
summary_3 = indicator_species_stats(3, insects_k3)
summary_3
```

## Insect Results
```{r}
bind_rows(
  summary_3,
  indicator_species_stats(6, insect_indicator_species(plant_and_insect_clusters$`6`)),
  indicator_species_stats(8, insect_indicator_species(plant_and_insect_clusters$`8`)),
  indicator_species_stats(9, insect_indicator_species(plant_and_insect_clusters$`9`)),
  indicator_species_stats(12, insect_indicator_species(plant_and_insect_clusters$`12`)),
  indicator_species_stats(15, insect_indicator_species(plant_and_insect_clusters$`15`)))
```

```{r}
insects_k8 = insect_indicator_species(plant_and_insect_clusters$`8`)
```

Generalists
```{r}
insects_k8$sign[is.na(insects_k8$sign$p.value),]
```

```{r}
summary(insects_k8)
```

## Exclude Generic ANY_SPECIES groupings
```{r}
insects_no_generics_per_site = read_input_csv('insect-presence.csv') %>% 
  filter(!(species %in% INSECT_GENERIC_EXCLUSIONS)) %>%
  to_presence_dataframe() %>% 
  include_sites_with_no_presence_record(plant_and_insect_clusters$title) %>% 
  arrange(title)
insects_no_generics_per_site_matrix = to_indicator_species_matrix(insects_no_generics_per_site)

insects_no_generics_indicator_species = function(cluster_assignment) {indicator_species(insects_no_generics_per_site_matrix, cluster_assignment)}
```
```{r}
bind_rows(
  summary_3,
  indicator_species_stats(6, insects_no_generics_indicator_species(plant_and_insect_clusters$`6`)),
  indicator_species_stats(8, insects_no_generics_indicator_species(plant_and_insect_clusters$`8`)),
  indicator_species_stats(9, insects_no_generics_indicator_species(plant_and_insect_clusters$`9`)),
  indicator_species_stats(12, insects_no_generics_indicator_species(plant_and_insect_clusters$`12`)),
  indicator_species_stats(15, insects_no_generics_indicator_species(plant_and_insect_clusters$`15`)))
```

## Exclude Generic Bumblebee groupings
```{r}
insects_no_bumblebee_generics_per_site = read_input_csv('insect-presence.csv') %>% 
  filter(!(species %in% INSECT_GENERIC_EXCLUSIONS)) %>%
  filter(!(species %in% BUMBLEBEE_GENERIC_EXCLUSIONS)) %>%
  to_presence_dataframe() %>% 
  include_sites_with_no_presence_record(plant_and_insect_clusters$title) %>% 
  arrange(title)
insects_no_bumblebee_generics_per_site_matrix = to_indicator_species_matrix(insects_no_bumblebee_generics_per_site)

insects_no_bumblebee_generics_indicator_species = function(cluster_assignment) {indicator_species(insects_no_bumblebee_generics_per_site_matrix, cluster_assignment)}
```

```{r}
bind_rows(
  summary_3,
  indicator_species_stats(6, insects_no_bumblebee_generics_indicator_species(plant_and_insect_clusters$`6`)),
  indicator_species_stats(8, insects_no_bumblebee_generics_indicator_species(plant_and_insect_clusters$`8`)),
  indicator_species_stats(9, insects_no_bumblebee_generics_indicator_species(plant_and_insect_clusters$`9`)),
  indicator_species_stats(12, insects_no_bumblebee_generics_indicator_species(plant_and_insect_clusters$`12`)),
  indicator_species_stats(15, insects_no_bumblebee_generics_indicator_species(plant_and_insect_clusters$`15`)))
```

# Plant Indicators
```{r}
bind_rows(
  indicator_species_stats(3, plant_indicator_species(plant_and_insect_clusters$`3`)),
  indicator_species_stats(6, plant_indicator_species(plant_and_insect_clusters$`6`)),
  indicator_species_stats(8, plant_indicator_species(plant_and_insect_clusters$`8`)),
  indicator_species_stats(9, plant_indicator_species(plant_and_insect_clusters$`9`)),
  indicator_species_stats(12, plant_indicator_species(plant_and_insect_clusters$`12`)),
  indicator_species_stats(15, plant_indicator_species(plant_and_insect_clusters$`15`)))
```

```{r}
plants_k8 = plant_indicator_species(plant_and_insect_clusters$`8`)
```

Generalists
```{r}
plants_k8$sign[is.na(plants_k8$sign$p.value),]
```

```{r}
summary(plants_k8)
```

# Bird Indicators
```{r}
bind_rows(
  indicator_species_stats(3, bird_indicator_species(bird_clusters$`3`)), 
  indicator_species_stats(4, bird_indicator_species(bird_clusters$`4`)), 
  indicator_species_stats(6, bird_indicator_species(bird_clusters$`6`)), 
  indicator_species_stats(7, bird_indicator_species(bird_clusters$`7`)), 
  indicator_species_stats(8, bird_indicator_species(bird_clusters$`8`)), 
  indicator_species_stats(9, bird_indicator_species(bird_clusters$`9`)), 
  indicator_species_stats(12, bird_indicator_species(bird_clusters$`12`)),
  indicator_species_stats(15, bird_indicator_species(bird_clusters$`15`)))
```

```{r}
birds_k9 = plant_indicator_species(bird_clusters$`9`)
```

Generalists
```{r}
birds_k9$sign[is.na(birds_k9$sign$p.value),]
```

```{r}
summary(birds_k9)
```
